#!/bin/bash
GOOS=linux go build -o main get.go
zip get.zip main

GOOS=linux go build -o main post.go
zip post.zip main

GOOS=linux go build -o main put.go
zip put.zip main

GOOS=linux go build -o main delete.go
zip delete.zip main